[package]
name = "virtsynth"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.0"
egui_plot = "0.29.0"
cpal = { version = "0.15.3", features = ["jack"] }
image = { version = "0.25.2", default-features = false, features = ["png"] }

[profile.dev]
strip = "debuginfo"